version: '3'

services:
  dashboard:
    build: betagr-dashboard/server
    ports:
      - 5000:5000
    command: python ./app.py
    depends_on:
      liquibase
    env_file:
      .env

  sso:
    build: betagr-sso/server
    ports:
      - 8080:8080
    command: python ./app.py8
    depends_on:
      liquibase
    env_file:
      .env

  aggregator:
    build: betagr-aggregator/server
    ports:
      - 3000:3000
    command: python ./app.py
    depends_on:
      liquibase
    env_file:
      .env

  parser:
    build: betagr-parser/server
    ports:
      - 8000:8000
    command: python ./app.py
    depends_on:
      liquibase
    env_file:
      .env

  liquibase:
        image: "webdevops/liquibase:postgres"
        volumes:
            - .:/liquibase
        environment:
            - LIQUIBASE_CHANGELOG=${LIQUIBASE_CHANGELOG}
            - LIQUIBASE_URL=jdbc:postgresql://host.docker.internal:${POSTGRES_PORT}/${POSTGRES_DB}
            - LIQUIBASE_USERNAME=${POSTGRES_USER}
            - LIQUIBASE_PASSWORD=${POSTGRES_PASSWORD}
